from models import COGS_Model
from domain.COGS_Domain import COGS_Domain
from dto.COGS_DTO import COGS_DTO
from flask_sqlalchemy import SQLAlchemy


def create_cogs(db: SQLAlchemy) -> None:
    costs = [
        {
            "num_meals": 6,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.120,
            "ice": 0.548,
            "num_boxes": 1,
            "is_local": False,
        },
        {
            "num_meals": 7,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.817,
            "ice": 0.470,
            "num_boxes": 1,
            "is_local": False,
        },
        {
            "num_meals": 8,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.590,
            "ice": 0.411,
            "num_boxes": 1,
            "is_local": False,
        },
        {
            "num_meals": 9,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.827,
            "ice": 0.731,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 10,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.544,
            "ice": 0.658,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 11,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.313,
            "ice": 0.598,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 12,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.120,
            "ice": 0.548,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 13,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.957,
            "ice": 0.506,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 14,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.817,
            "ice": 0.470,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 15,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.696,
            "ice": 0.439,
            "num_boxes": 3,
            "is_local": False,
        },
        {
            "num_meals": 16,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.590,
            "ice": 0.411,
            "num_boxes": 3,
            "is_local": False,
        },
        {
            "num_meals": 17,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.245,
            "ice": 0.580,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 18,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.120,
            "ice": 0.548,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 19,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 2.008,
            "ice": 0.519,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 20,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.908,
            "ice": 0.493,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 21,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.817,
            "ice": 0.470,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 22,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.735,
            "ice": 0.448,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 23,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.659,
            "ice": 0.429,
            "num_boxes": 2,
            "is_local": False,
        },
        {
            "num_meals": 24,
            "ingredient": 3,
            "core_packaging": 0.459,
            "kitchen": 1.3,
            "chef": 0,
            "box": 1.590,
            "ice": 0.411,
            "num_boxes": 3,
            "is_local": False,
        },
    ]
    for cost in costs:
        cogs_dto = COGS_DTO(cogs_json=cost)
        cogs_domain = COGS_Domain(cogs_object=cogs_dto)
        cogs_model = COGS_Model(cogs_domain=cogs_domain)
        db.session.add(cogs_model)
    db.session.commit()
